server:
  port: 8763

spring:
  application:
    name: eureka-client-mybatis
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/config?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&failOverReadOnly=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

## Mybatis 配置 
mybatis:
  typeAliasesPackage: cn.hz.qbd.cloud.eureka.client.mybatis.**.entity
  mapperLocations: classpath*:cn/hz/qbd/cloud/eureka/client/mybatis/**/mapper/*.xml
# 驼峰命名规范 如：数据库字段是  order_id 那么 实体字段就要写成 orderId
  configuration:
    map-underscore-to-camel-case: true
#初始化自定义的接口mapper
mapper:
  mappers: cn.hz.qbd.cloud.eureka.client.mybatis.common.BaseMapper
  notEmpty: false # 设置 insert 和 update 中，是否判断字符串类型!='
  identity: MYSQL # 主键自增回写方法,默认值MYSQL,详细说明请看文档
  enum-AsSimpleType: true # 枚举按简单类型处理
########## 分页插件 ##########
pagehelper:
  helperDialect: mysql
  params: count=countSql
  reasonable: false
  supportMethodsArguments: true

debug: true
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: error
        web: DEBUG
    cn.hz.qbd.cloud.eureka.client.mybatis: DEBUG
    jdbc.sqltiming: DEBUG